### PR TITLE
Autoformatted with black

### PR DESCRIPTION
**Pull request by wchen-github**
# Pull Request Template

## Description

Please include a list of changes, relevant information, context and new dependencies.

Fixes: # (issue)

## Changes

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to not work as expected)
- [ ] Documentation update

**Configuration**:
* Archai version:
* Environment:
* OS:

## Final checks:

- [ ] Follows guidelines of project
- [ ] Self-review of code
- [ ] Commented code in hard-to-understand areas
- [ ] Corresponding changes to the documentation
- [ ] Changes generate no new warnings
- [ ] Dependent changes have already been merged
- [ ] Checked code correction any misspellings

### CODE REVIEW

**Comment by lovettchris** [comment]
Thanks, flake8 finds a few more:

(archai) D:\git\microsoft\archai\archai\tasks\facial_landmark_detection>flake8 .
.\search_space.py:32:1: C901 '_gen_tv_mobilenet' is too complex (13)
.\search_space.py:191:24: E711 comparison to None should be 'if cond is None:'
.\search_space.py:201:25: E711 comparison to None should be 'if cond is not None:'
.\search_space.py:235:16: E711 comparison to None should be 'if cond is not None:'
.\search_space.py:307:20: E711 comparison to None should be 'if cond is None:'
.\search_space.py:317:21: E711 comparison to None should be 'if cond is not None:'
.\search_space.py:332:20: E711 comparison to None should be 'if cond is None:'
.\search_space.py:340:21: E711 comparison to None should be 'if cond is not None:'
.\search_space.py:362:9: F841 local variable 'pred' is assigned to but never used
.\search_space.py:363:9: F841 local variable 'model_summary' is assigned to but never used
.\train.py:126:5: F841 local variable 'val_resize_size' is assigned to but never used
.\train.py:151:1: C901 'train' is too complex (30)
.\train.py:166:5: F841 local variable 'train_dir' is assigned to but never used
.\train.py:170:5: F841 local variable 'collate_fn' is assigned to but never used

**Comment by wchen-github** [comment]
Fixed the rest except for these two. Not worth it, IMO. 

.\search_space.py:32:1: C901 '_gen_tv_mobilenet' is too complex (13)
.\train.py:151:1: C901 'train' is too complex (30)

**Comment by lovettchris** [comment]
> Fixed the rest except for these two. Not worth it, IMO.
> 
> .\search_space.py:32:1: C901 '_gen_tv_mobilenet' is too complex (13) .\train.py:151:1: C901 'train' is too complex (30)

yeah, I agree, those warnings can be hard to get rid of without major refactoring.  But the _gen_tv_mobilenet one is easy, just pop the embedded function _make_divisible out, it doesn't need to be embedded anyway since it is not using any of those local variables.

**Review by lovettchris — APPROVED** [review]

**Comment by wchen-github** [comment]
That would be a matter of taste. ;)

**Pull request merged**
