### PR TITLE
pr(archai): Starts `models` refactoring and adds new module for OPT and OPT-Flex.

### PR DESCRIPTION
**Pull request by gugarosa**
# Pull Request Template

## Description

* Implements the first step for re-factoring the `models` module, which will clear out some unused code and makes it easier to extend for future models, including pre-trained models from Huggingface's.
* Adds support for OPT and OPT-Flex using the new introduced structure.

## Changes

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Tests

The unitary tests suite will be built.

**Configuration**:
* Archai version: 0.6.5
* Platform: Windows
* Environment: Python 3.7

## Final checks:

- [X] Follows guidelines of project
- [X] Self-review of code
- [X] Commented code in hard-to-understand areas
- [X] Corresponding changes to the documentation
- [X] Changes generate no new warnings
- [X] Added tests to assert changes
- [X] Dependent changes have already been merged
- [X] Checked code correction any misspellings

### CODE REVIEW

**Comment by sytelus** [comment]
Entire model.py is changed? Can you please describe the changes you are making?

**Comment by gugarosa** [comment]
The idea is to improve our current base model implementation found here: https://github.com/microsoft/archai/blob/master/archai/nlp/models/model_base.py

The changes are minimal, mostly a smarter way to calculate the number of parameters. The diff is big because the changes are in a new file, mainly to prevent deprecating the old file. We will definitely deprecate it in the future, but I would say that we should wait a while to see if the refactor is stable.

**Comment by sytelus** [comment]
If changes are small, why do we need new file? I am bit confused. Are there breaking changes in APIs? Also, the model_base is named that way because we want it to be inheritable.

**Comment by gugarosa** [comment]
It is the beginning of a refactor, which might break previous functionalities. Thus, I opted to start the refactor in chunks of new files and slowly replace the old ones as we proceed with the code.

With that, we will be avoiding to break what we current have, specially the production-related code. And meanwhile, we will be updating with new features.

**Pull request closed without merging**
